plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
}

dependencies {
    def props = new Properties()
    file("../gradle.properties").withInputStream { props.load(it) }

    implementation("org.springframework.boot:spring-boot-gradle-plugin:${props['springBootVersion']}")
    implementation("io.spring.gradle:dependency-management-plugin:${props['springDependencyManagementVersion']}")
    implementation("com.diffplug.spotless:spotless-plugin-gradle:${props['spotlessVersion']}")
}

gradlePlugin {
    plugins {
        spotlessConvention {
            id = 'spotless-convention'
            implementationClass = 'SpotlessConventionPlugin'
        }
    }
}
